# docker-compose.yml
version: "3.5"
services:
  redis:
    image: redis:5
    container_name: redis-server
    hostname: redis-server
    ports:
      - 16379:6379
    volumes:
      - "${REDIS_DIR}/conf:/usr/local/etc/redis"
      - "${REDIS_DIR}/data:/data"
    command:
      redis-server

  mysql:
    image: mysql:5.7
    container_name: mysql-server
    hostname: mysql-server
    ports:
      - 13306:3306
    volumes:
      - "${MYSQL_DIR}/data:/var/lib/mysql"
      - "${MYSQL_DIR}/conf.d:/etc/mysql/conf.d"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  nacos:
    image: nacos/nacos-server:latest
    container_name: registry-server
    hostname: registry-server
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - "${NACOS_DIR}/logs/:/home/nacos/logs"
    ports:
      - "18848:8848"